CREATE DATABASE MS_02_2022_HISTORIAL;

USE MS_02_2022_HISTORIAL;

CREATE TABLE historial_pago (
  ID_HISTORIAL_PAGO BIGINT PRIMARY KEY AUTO_INCREMENT,
  NOMBRE VARCHAR(120) NOT NULL,
  FECHA VARCHAR(255),
  HORA VARCHAR(255),
  ID_BOLETA BIGINT,
  ESTADO VARCHAR(255)
);
