CREATE DATABASE IF NOT EXISTS MS_02_2022_BOLETAS;

USE MS_02_2022_BOLETAS;

CREATE TABLE boleta (
  ID_BOLETA INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(120) NOT NULL,
  FECHA DATE,
  ID_CLIENTE INT,
  ESTADO VARCHAR(20)
);

CREATE TABLE detalle_boleta (
  ID_DETALLE_BOLETA INT AUTO_INCREMENT PRIMARY KEY,
  UNIDAD VARCHAR(50) NOT NULL,
  ID_BOLETA INT,
  ID_PRODUCTO INT,
  ESTADO VARCHAR(20)
);
