# Sever
server:
  port: 8891

# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
           
# Matricula de Microservicios
spring:
  cloud:
    gateway:
      discovery.locator:    #A           
          enabled: true           
          lowerCaseServiceId: true
#      routes:
#        - id: ms-ventas-gestion-productos
#          uri: lb://ms-server-productos
#          predicates:
#           - Path=/v1/productos/**
#          filters:
#           - AuthFilter
        
#      - id: albums
#        uri: https://jsonplaceholder.typicode.com/albums
#        predicates:
#        - Path=/albums

# Activacion de endpoints
management:
     endpoints:
       web:
         exposure:
           include: '*'
     endpoint:
       gateway:
          enabled: true
       health:
         show-details: always
         
         
         