server:
  port: 8083
    
# Postgres SQL #l
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MS_02_2022_CATEGORIAS
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
# Spring Boot Admin
  boot:
     admin:
        client:
           url: http://localhost:8890

# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
         