server:
  port: 8081
    
# My SQL #
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MS_02_2022_PRODUCTOS
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    
# Spring Boot Admin
  boot:
     admin:
        client:
           url: http://localhost:8890
    
# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
         
# Actuator
management:
  endpoints:
     web:
       exposure:
         include: "*"
       