server:
  port: 8082
    
# My SQL #
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MS_02_2022_CLIENTES
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    
# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
    