server:
  port: 8083
    
# My SQL #
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MS_02_2022_CATEGORIAS
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
         