server:
  port: 8082
    
# Oracle #
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: MS_02_2022_CLIENTES
    password: 123456
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        
# Spring Boot Admin
  boot:
     admin:
        client:
           url: http://localhost:8890
        
    
# Registry Client
eureka:
   client:
      registryFetchIntervalSeconds: 5
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
         
# Actuator
management:
  endpoints:
     web:
       exposure:
         include: "*"
    